preset = "C:/Users/yukimemi/src/github.com/yukimemi/pj-presets/rust-cli.toml"
base_dir = "C:/Users/yukimemi/src/github.com/yukimemi/pj-presets"
applied_at = "2026-05-04T04:47:05.8870479Z"

[[templates]]
source = "../pj-base"
rev = "local"
version = "0.1.0"

[[templates]]
source = "../pj-rust"
rev = "local"
version = "0.1.0"

[[templates]]
source = "../pj-rust-cli"
rev = "local"
version = "0.1.1"

[files.".editorconfig"]
content_hash = "58657ee086523ff34b0b1aef4da8a50a7489d1219ed206ddd774794f493275bb"
once_applied = true

[files.".github/workflows/ci.yml"]
content_hash = "d7e72cafb216e66a258c9ff27fe8d896d02b14d332f462084df492638211e414"

[files."Makefile.toml"]
content_hash = "516be91cf3e29dd0b82cdda33cafc3c278af8299c32e21dcee8540bc8480c3f6"

[files."rust-toolchain.toml"]
content_hash = "9eac3c057320afbad00022718e0c14731122b4c3f28abd2dc702846244c39f66"
